apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://microservices-prometheus:9090
    isDefault: true
    editable: true
    version: 1
    jsonData:
      timeInterval: 15s
      httpMethod: GET
      httpHeaderName1: X-Scope-OrgID
      httpHeaderValue1: 1
      httpHeaderName2: X-Scope-OrgID
      httpHeaderValue2: 1
      httpHeaderName3: X-Scope-OrgID
      httpHeaderValue3: 1
      httpHeaderName4: X-Scope-OrgID
      httpHeaderValue4: 1
      httpHeaderName5: X-Scope-OrgID
      httpHeaderValue5: 1
      httpHeaderName6: X-Scope-OrgID
      httpHeaderValue6: 1
      httpHeaderName7: X-Scope-OrgID
      httpHeaderValue7: 1
      httpHeaderName8: X-Scope-OrgID
      httpHeaderValue8: 1
      httpHeaderName9: X-Scope-OrgID
      httpHeaderValue9: 1
      httpHeaderName10: X-Scope-OrgID
      httpHeaderValue10: 1
      httpHeaderName11: X-Scope-OrgID 