global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'monolith'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['monolith:8080']

  - job_name: 'jmeter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9270'] 