global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'student-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['student-service:8081']

  - job_name: 'course-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['course-service:8082']

  - job_name: 'enrollment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['enrollment-service:8083'] 